### ISSUE TITLE
Lattice Connector Doesn't Work in FireFox

### ISSUE THREAD

**Issue by VojtechPlasil** [GridPlus/eth-lattice-keyring#30]
Lattice cannot be connected to MetaMask on FF.
How to get there:
1. Connect Hardware Wallet
2. Lattice1
3. Lattice Connector opens, input Device ID and pass
4. Input secret
5. Gets stuck afterwards on this screen:
![image](https://user-images.githubusercontent.com/33695749/156653794-36f31b0e-4de8-4601-9f10-72a00b68f461.png)
And MetaMask shows "Lattice Connector Closed".

**Comment by alex-miller-0** [comment]
This appears to be a result of changing the keyring's URL from `wallet.gridplus.io` to `lattice.gridplus.io`, but not updating the manifest file in MetaMask. Will do that in the next MM merge

**Comment by alex-miller-0** [comment]
Fixed in: https://github.com/MetaMask/metamask-extension/pull/13834
