### ISSUE TITLE
Can not sign transaction build by legacy package

### ISSUE THREAD

**Issue by vvvvvv1vvvvvv** [GridPlus/eth-lattice-keyring#31]
Transactions build via legacy package `ethereumjs-tx` use `tx.getChainId` to get chainId and will return a `number`.

So when we submit a legacy transaction to keyring will goes in https://github.com/GridPlus/eth-lattice-keyring/blob/master/index.js#L795, but `signTransaction` use the return value as `number.toString('hex')` https://github.com/GridPlus/eth-lattice-keyring/blob/master/index.js#L194 this will cause an exception like: `RangeError: toString() radix argument must be between 2 and 36`

**Comment by vvvvvv1vvvvvv** [comment]
btw actually `this._getEthereumJsChainId(tx).toString('hex')` is useless since `this._getEthereumJsChainId(tx)` already revert to a hex string without the 0x prefix, so I think fix as below should be useful
```typescript
if (typeof tx.getChainId === 'function') {
    return tx.getChainId().toString('16');
}
```

**Comment by alex-miller-0** [comment]
Thank you for this! Will fix
