### ISSUE TITLE
Explore storing ABI data

### ISSUE THREAD

**Issue by alex-miller-0** [GridPlus/eth-lattice-keyring#52]
Rather than looking up ABI definitions every time the user makes a transaction request, it would be much more efficient to store ABI definitions that have been fetched and used to sign transactions in the past.

We should have a fair bit of localstorage to use in MetaMask and may want to use it for this purpose.

Thoughts @douglance ?

**Comment by douglance** [comment]
Looks like we could use this lib to add caching relatively easily https://www.npmjs.com/package/superagent-cache-plugin
